version: '3'
services:
  web:
    image: mongo-server
    build: .
    command: 'node src/main.js'
    ports:
      - '3000:3000'
    depends_on:
      - 'mongo'
  mongo:
    image: 'mongo:4.2'
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-volume:/usr/src/app
