version: '3'
services:
  mongodb:
    image: 'mongo:4.2'
    container_name: 'mongodb'
    environment:
      - MONGO_INITDB_DATABASE=uncached-data
      - MONGO_INITDB_ROOT_USERNAME=iamcreator
      - MONGO_INITDB_ROOT_PASSWORD=mongopass
    volumes:
      - ./db-init.js:/docker-entrypoint-initdb.d/db-init.js:ro
      - ./mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'
